### PR TITLE
Adding Browser-based tests

### PR DESCRIPTION
**Pull request by kmader**
adding casper-based browser tests (based on the gist from @ellisonbg https://gist.github.com/ellisonbg/3329929)

### CODE REVIEW

**Comment by betatim** [comment]
Should we try and finish this off or close/take a new approach?

[This is the robot framework](https://github.com/datakurre/robotkernel/issues/2) I was talking about that others use to do UI based testing.

**Comment by kmader** [comment]
Any examples of repos using Robot with Travis? 
Do we just pip install, add the robot kernel, and then nbconver a robot notebook?

**Comment by betatim** [comment]
Good question. I will dig around a bit.

**Comment by datakurre** [comment]
@betatim FYI. I've now made a release of robotkernel and for me it seems that nbconvert should work. Note that if you use headless Firefox, geckodriver must be downloaded into path separately.

**Comment by bollwyvl** [comment]
> geckodriver must be downloaded into path separately

If you're on the conda bus, you still have to install `firefox` and `chrome` yourself, but...
- [geckodriver](https://anaconda.org/conda-forge/geckodriver)
- [chromedriver](https://anaconda.org/conda-forge/python-chromedriver-binary)
- [robotframework-seleniumlibrary](https://anaconda.org/conda-forge/robotframework-seleniumlibrary)

... are all conda-forged.

Here are some examples of testing Jupyter(Lab) with robot:
- [jyve](https://github.com/deathbeds/jyve/blob/master/tests/resources/Lab.robot)
- [jupyterlab-fonts](https://github.com/deathbeds/jupyterlab-fonts/blob/master/tests/acceptance/Editor.robot)

I keep meaning to capture all of these in a library, but continue to eat the copy-pasta.

**Comment by kmader** [comment]
@datakurre @bollwyvl thanks for the links, they look like a great start. I will close this PR and make a new one since my code here is not a great start. I might come back to you if it all blows up but it seems straightforward enough.

**Pull request closed without merging**
